### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Crypt97** [SchdowNVIDIA/EC-TableUI#1]
1. hold up Diamond Pickexe, Axe, etc. and click Enchantment Table.
2 . Look at the console message.

`18:49:23 <Server thread/Critical> TypeError: "Argument 1 passed to jojoe77777\FormAPI\SimpleForm::__construct() must be of the type integer, object given, called in C:\Users\crypt\Desktop\Altay-stable2\plugins\EC-TableUI-master\src\SchdowNVIDIA\ECTUI\EventListener.php on line 186" (EXCEPTION) in "plugins/FormAPI-master/src/jojoe77777/FormAPI/SimpleForm" at line 29
18:49:23 <Server thread/Debug> #0 plugins/EC-TableUI-master/src/SchdowNVIDIA/ECTUI/EventListener(186): jojoe77777\FormAPI\SimpleForm->__construct(Closure object)
18:49:23 <Server thread/Debug> #1 plugins/EC-TableUI-master/src/SchdowNVIDIA/ECTUI/EventListener(209): SchdowNVIDIA\ECTUI\EventListener->openECTUI(pocketmine\Player object, pocketmine\item\Pickaxe object, pocketmine\block\EnchantingTable object)
18:49:23 <Server thread/Debug> #2 src/pocketmine/plugin/MethodEventExecutor(38): SchdowNVIDIA\ECTUI\EventListener->onTouch(pocketmine\event\player\PlayerInteractEvent object)
18:49:23 <Server thread/Debug> #3 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(SchdowNVIDIA\ECTUI\EventListener object, pocketmine\event\player\PlayerInteractEvent object)
18:49:23 <Server thread/Debug> #4 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerInteractEvent object)
18:49:23 <Server thread/Debug> #5 src/pocketmine/level/Level(1990): pocketmine\event\Event->call()
18:49:23 <Server thread/Debug> #6 src/pocketmine/Player(2575): pocketmine\level\Level->useItemOn(pocketmine\math\Vector3 object, pocketmine\item\Pickaxe object, integer 4, pocketmine\math\Vector3 object, pocketmine\Player object, boolean 1)
18:49:23 <Server thread/Debug> #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(156): pocketmine\Player->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
18:49:23 <Server thread/Debug> #8 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(158): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
18:49:23 <Server thread/Debug> #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(116): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
18:49:23 <Server thread/Debug> #10 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
18:49:23 <Server thread/Debug> #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(116): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
18:49:23 <Server thread/Debug> #12 src/pocketmine/Player(3378): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
18:49:23 <Server thread/Debug> #13 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
18:49:23 <Server thread/Debug> #14 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 46.139.254.142 50447, raklib\protocol\EncapsulatedPacket object, integer 0)
18:49:23 <Server thread/Debug> #15 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
18:49:23 <Server thread/Debug> #16 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
18:49:23 <Server thread/Debug> #17 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
18:49:23 <Server thread/Debug> #18 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
18:49:23 <Server thread/Debug> #19 src/pocketmine/Server(2392): pocketmine\snooze\SleeperHandler->sleepUntil(double 1559411363.3122)
18:49:23 <Server thread/Debug> #20 src/pocketmine/Server(2297): pocketmine\Server->tickProcessor()
18:49:23 <Server thread/Debug> #21 src/pocketmine/Server(1875): pocketmine\Server->start()
18:49:23 <Server thread/Debug> #22 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\crypt\Desktop\Altay-stable2\, string C:\Users\crypt\Desktop\Altay-stable2\plugins\)
18:49:23 <Server thread/Debug> #23 (1): require_once(string phar://C:/Users/crypt/Desktop/Altay-stable2/Altay.phar/src/pocketmine/PocketMine.php)
`

**Comment by justin-eckenweber** [comment]
Well this Plugin is for PocketMine-MP Servers. \Altay-stable2\ as i can see you're using Altay.

**Comment by justin-eckenweber** [comment]
It's working flawlessly with Pocketmine. 
http://prntscr.com/nwfsei
