### ISSUE TITLE
Bow

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [SchdowNVIDIA/EC-TableUI#5]
efficiency, fortune and unbreaking enchantment for bow. I think its the wrong enchantment xd

**Comment by TDMidkwhatisxd** [comment]
Just checked version is 1.1.0 pre and i didnt touch the config :o

**Comment by TDMidkwhatisxd** [comment]
Hahaha found the issue
    public function initEnchantments() {
        // registering some missing enchantments
        Enchantment::registerEnchantment(new Enchantment(Enchantment::FORTUNE, "Fortune", Enchantment::RARITY_UNCOMMON, Enchantment::SLOT_DIG, Enchantment::SLOT_NONE, 3));
        Enchantment::registerEnchantment(new Enchantment(Enchantment::LOOTING, "Looting", Enchantment::RARITY_UNCOMMON, Enchantment::SLOT_SWORD, Enchantment::SLOT_NONE, 3));
        $this->swordEnchantments = $this->getConfig()->get("swordEnchantments");
        $this->armorEnchantments = $this->getConfig()->get("armorEnchantments");
        $this->toolEnchantments = $this->getConfig()->get("toolEnchantments");
        $this->bowEnchantments = $this->getConfig()->get("toolEnchantments");
    }

**Comment by TDMidkwhatisxd** [comment]
I will fix it for myself, because for me github is laggy to make pull request :)
Still didnt work :o

**Comment by TDMidkwhatisxd** [comment]
just edited a line instance of Bow, and edited to a random name, it seems that bow = tool :))))
Weird,  i will play with the code a little to see what i get lol

**Comment by TDMidkwhatisxd** [comment]
My fix, i moved the elesif Instance of Bow line,  in top of instance of tool to check first if its bow then tool.
It seems that bow can be instance of Tool too omg  xd

**Comment by SchdowNVIDIA** [comment]
Okay, i'm watching into the pull request and merge it if needed :)

**Comment by justin-eckenweber** [comment]
Oh, i see i will fix this later :)
